version: '3'
services:
  db:
    image: docker.io/postgres:latest
    container_name: db-quotes
    restart: always
    env_file: .env 
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    volumes:
      - ./config/postgress:/docker-entrypoint-initdb.d 
    ports:
      - '${PG_PORT}:5432'

  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file: .env
    restart: always
    ports:
      - '${MG_PORT}:27017'
  
  web-quotes:
    build: 
      context: services/quotes
      dockerfile: Dockerfile
    container_name: web-quotes
    ports:
      - 5000:5000
    depends_on:
      - db

  web-alpha-flatten:
    build: 
      context: services/alpha-flatten
      dockerfile: Dockerfile
    container_name: web-alpha-flatt
    ports:
      - 5001:5001
    depends_on:
      - mongodb
